# fly.toml app configuration file generated for nwc-mint on 2024-07-24T00:37:17+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwc-mint'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  source = 'nwc_mint_data'
  destination = '/data'
  initial_size = '1'

